function getRandInt(num: number) {
  return Math.floor(Math.random() * num);
}
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const rand = getRandInt(2);
  // console.log("Rnad in Layout", rand);
  // if (rand === 1) {
  //   throw new Error("1 is from Layout");
  // }
  return (
    <html lang="en">
      <body>
        <h1>Docs Root Layout</h1>
        {children}
      </body>
    </html>
  );
}
